name: bandersnatch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  flutter_tts: ^3.6.3
  speech_to_text: ^7.3.0
  google_fonts: ^5.0.0
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/images/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/personajes/bardock.jpg
    - assets/images/personajes/broly.jpeg
    - assets/images/personajes/bulma.jpg
    - assets/images/personajes/celljr.png
    - assets/images/personajes/gogeta.jpg
    - assets/images/personajes/gohan.jpg
    - assets/images/personajes/goku.jpg
    - assets/images/personajes/gokuDios.jpg
    - assets/images/personajes/goten.jpg
    - assets/images/personajes/gotenks.png
    - assets/images/personajes/kaiohnorte.jpg
    - assets/images/personajes/kamisama.jpeg
    - assets/images/personajes/krilin.jpg
    - assets/images/personajes/majinbuu.jpeg
    - assets/images/personajes/milk.jpg
    - assets/images/personajes/picolo.jpg
    - assets/images/personajes/roshi.jpg
    - assets/images/personajes/superbuu.jpg
    - assets/images/personajes/trinks.png
    - assets/images/personajes/vegeta.jpg
    - assets/images/personajes/vegetto.jpg
    - assets/images/personajes/yamcha.jpg
    - assets/music/musica.mp3
    - assets/images/icon/icon.png
    #   - images/a_dot_ham_2x.png


  #- assets/audio/background_music.mp3
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
